### ISSUE TITLE
[Flow] 创建 Flow 添加示例 YML 配置

### ISSUE THREAD

**Issue by yang-guo-2016** [FlowCI/flow-platform#188]
在创建 flow 时第三步填写 YML 配置时，默认给出 hello world 示例

```
# flow.ci templates

flow:
  - envs:
      FLOW_WELCOME_MESSAGE: "hello.world"
      
    steps:
      - name: Init
        script: |
          echo ${FLOW_WELCOME_MESSAGE}
```
