### ISSUE TITLE
Plugin 仓库具体描述的 YML 定义

### ISSUE THREAD

**Issue by yunheli** [FlowCI/flow-platform#194]
- YML 从远程仓库获取
- YML 对象转换保存

**Comment by yunheli** [comment]
```
name: fir-cli
tag: 1.0.1
description: Posts Wercker build/deploy status to a Slack channel.
labels:
  - notification
  - webhook
  - slack
inputs:
  name:
    type: string
    default: admin
    required: true
  password:
    type: string
    required: true
  age:
    type: integer
    required: true
  isMarried:
    type: boolean
    required: true
    default: true
  cities:
    type: list
    required: false
    values:
      - beijing
      - shanghai
      - nanjing
    default: beijing
outputs:
  - USER_NAME
  - PASSWORD
run: |
  bash ./run.sh
language: java
build: |
  mvn clean build -dist=xxxx
```
